### ISSUE TITLE
Create multiple zookeeper services and update zkhosts

### ISSUE THREAD

**Issue by ghost** [lucidworks/solr-helm-chart#1]
Right now it seems as though this chart only creates 1 service for zookeeper and because of this if you have one of the pods fail for zookeeper and its the leader, solr goes down for a few minutes.

I suggest having the chart create 3 services, 1 per zookeeper pod and then update the zkhosts accordingly. 

Each service could be similar to the one below.

```
kind: Service
apiVersion: v1
metadata:
  name: solr-zookeeper-0-service
  labels:
    app: zookeeper
spec:
  selector:
    statefulset.kubernetes.io/pod-name: solr-zookeeper-0
  ports:
  - protocol: TCP
    port: 2180
    targetPort: 2181
  type: ClusterIP
```
